name: EnderEX
version: '${project.version}'
softdepend: [Floodgate]
main: fr.infinitystudios.enderex.EnderEX
api-version: '1.21'
authors: [ InfinityStudios ]
website: https://vlxproject.fr
permissions:
  enderex.physicalopen:
    description: activate physical opening of the enderchests
    default: false
  enderex.commandopen:
    description: activate command opening of the enderchests
    default: false
  enderex.chest.1:
    description: open 1 row
    default: false
  enderex.chest.2:
    description: open 2 row
    default: false
  enderex.chest.3:
    description: open 3 row
    default: false
  enderex.chest.4:
    description: open 4 row
    default: false
  enderex.chest.5:
    description: open 5 row
    default: false
  enderex.chest.6:
    description: open 6 row
    default: false
  enderex.admin:
    description: admin perm
    default: op
  enderex.edit:
    description: edit other EC perm
    default: op
